export const ADD_CATEGORY_START = "ADD_CATEGORY_START";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAIL = "ADD_CATEGORY_FAIL";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";

export const FETCH_LOG_START = "FETCH_LOG_START";
export const FETCH_LOG_SUCCESS = "FETCH_LOG_SUCCESS";
export const FETCH_LOG_FAIL = "FETCH_LOG_FAIL";

export const ADD_ALBUM_START = "ADD_ALBUM_START";
export const ADD_ALBUM_SUCCESS = "ADD_ALBUM_SUCCESS";
export const ADD_ALBUM_FAIL = "ADD_ALBUM_FAIL";

export const REMOVE_ALBUM_START = "REMOVE_ALBUM_START";
export const REMOVE_ALBUM_SUCCESS = "REMOVE_ALBUM_SUCCESS";
export const REMOVE_ALBUM_FAIL = "REMOVE_ALBUM_FAIL";

export const LOGOUT = "LOGOUT";